"""product model has been added

Revision ID: 6b5100959d0f
Revises: 8544bef9bc81
Create Date: 2024-12-31 09:46:12.309131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b5100959d0f'
down_revision: Union[str, None] = '8544bef9bc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Product_name', table_name='Product')
    op.drop_table('Product')
    op.drop_index('ix_Clients_name', table_name='Clients')
    op.drop_table('Clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idNumber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', postgresql.ENUM('M', 'F', 'O', name='gender_enum'), autoincrement=False, nullable=True),
    sa.Column('Billing_Street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('City', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Postal_Code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Clients_pkey')
    )
    op.create_index('ix_Clients_name', 'Clients', ['name'], unique=False)
    op.create_table('Product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ref_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Product_pkey')
    )
    op.create_index('ix_Product_name', 'Product', ['name'], unique=False)
    # ### end Alembic commands ###
